services:
  # Banco de dados MySQL
  db:
    image: mysql:8.0
    container_name: minha-pagina-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cadastro
      MYSQL_USER: henriqueadmin
      MYSQL_PASSWORD: henriqueadmin
    volumes:
      - mysql_data:/var/lib/mysql
      - ./banco.sql:/docker-entrypoint-initdb.d/banco.sql
    command: --default-authentication-plugin=mysql_native_password

  # phpMyAdmin para gerenciar o banco
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pagina-web-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db

volumes:
  mysql_data: